### PR TITLE
Sponsor create product-vouchers

### PR DESCRIPTION
**Pull request by dev-rminds**

### CODE REVIEW

**Comment by maxvisser** [comment]
image

still shows product vouchers not generated from this dashboard page. Should be the same as other generator

**Comment by maxvisser** [comment]
we should show the price of each product here.
image

**Comment by aghimpu** [comment]
Regarding the dashboard page showing the product vouchers I couldn't replicate this issue.
More details for products are added though (price and organization).

**Comment by maxvisser** [comment]
I can send you test data

**Pull request closed without merging**
