### PR TITLE
up to -> up to and including

### PR DESCRIPTION
**Pull request by SjoerdHilhorst**

### CODE REVIEW

**Comment by maxvisser** [comment]
should check if all update routes have 'up to and including' on this branch; so we do not write 'up to including' if the date is not.

**Comment by SjoerdHilhorst** [comment]
could you clarify what you mean with update routes?

**Comment by maxvisser** [comment]
that the data which is returned from the api is aswell 'up to and including'; this pr only changes the text while I think we can be certain that the cases which are now changed still have dates which are 'up to'

**Comment by SjoerdHilhorst** [comment]
I think dan or somebody else has to check if this is correct

**Comment by dev-rminds** [comment]
Included in this PR https://github.com/teamforus/forus-backend/pull/1089

**Pull request closed without merging**
