### PR TITLE
Release v0.5.1

### PR DESCRIPTION
**Pull request by maxvisser**
changelog 
- fund labels: tags, taggables,

### CODE REVIEW

**Comment by maxvisser** [comment]
tested this branch; https://staging.api.forus.io/api/v1/platform/funds does not load

**Comment by aghimpu** [comment]
@maxvisser , I fixed it on the last commit (9b2fc6d)

**Comment by maxvisser** [comment]
- [ ] 9 https://github.com/teamforus/development/issues/223
- [ ] 8 -
- [ ] 7 -
- [ ] 6 -
- [ ] 5 - https://github.com/teamforus/development/issues/227
- [ ] 4 - https://github.com/teamforus/development/issues/226
- [ ] 3 - https://github.com/teamforus/development/issues/222
- [ ] 2 - https://github.com/teamforus/development/issues/225
- [ ] 1 - https://github.com/teamforus/development/issues/224

**Comment by maxvisser** [comment]
will prospone release. 6 and 7 also need testing; no time left in this service window.

**Pull request merged**
