### PR TITLE
feature fund-request messages

### PR DESCRIPTION
**Pull request by dev-rminds**
## Developers checklist
- [x] **Autotests are passed locally**
- [x] **Migration rollback works** - if there is migration, check rollback
- [x] **Autotests are added**:
   - bugfix - unit/feature test for this scenario if possible
   - new small/medium feature - simple feature test for positive scenarios

## QA checklist
- [ ] **Translations are done**
- [ ] **Endpoint is fast on dump** - if there is new endpoint or changed query, endpoints that are using changed query - working fast on production dump, <2s

### CODE REVIEW

**Comment by irinaBerendeeva87** [comment]
@dev-rminds please solve the issue with backend. When I try to log in in in dev env of Eemsdelta I catch 500 error 
Screenshot 2024-07-15 at 09 36 14

**Comment by dev-rminds** [comment]
> @dev-rminds please solve the issue with backend. When I try to log in in in dev env of Eemsdelta I catch 500 error Screenshot 2024-07-15 at 09 36 14

@lexlog could you please check permissions to `storage/app` on the dev server?

**Comment by dev-rminds** [comment]
@lexlog probably related to webuser running under www-data and cron using a different user.

**Comment by RobinMeles** [comment]
Called with @dev-rminds and he added a permission script. Problem was indeed related due to cron was running under user 'root' and templates were running under different user.

Script is added on dev and demo. I also added these steps to check in future to the [configuration documentation](https://docs.google.com/document/d/1FybnfGjw8tqTDjM2j-AbHK5YbsJq0fN3No6GSFnC_FE/edit#heading=h.gdehm6vwwko7)

**Comment by irinaBerendeeva87** [comment]
I double-checked and the issue is solved)

**Review by irinaBerendeeva87 — APPROVED** [review]
Checked and approved

**Pull request merged**
