### PR TITLE
Fund providers resource, add employees information

### PR DESCRIPTION
**Pull request by aghimpu**
https://github.com/teamforus/forus/issues/1488

### CODE REVIEW

**Comment by maxvisser** [comment]
why does it filter on validator role?

**Comment by aghimpu** [comment]
> why does it filter on validator role?

because I believe it did before the refactoring, I checked past commits

**Comment by maxvisser** [comment]
We can just show all employees

**Comment by aghimpu** [comment]
https://github.com/teamforus/forus-frontend/pull/1103

**Pull request merged**
