### PR TITLE
Epic.actions

### PR DESCRIPTION
**Pull request by dev-rminds**

### CODE REVIEW

**Comment by jamalv** [comment]
There's a question about emails (needed for acceptance test) does the requester already recieve an email for each transaction like with budget vouchers? We should inform users about usage and availability.

"You have used x of x"

**Comment by jamalv** [comment]
@maxvisser why is requesting displayed twice here?

Screenshot 2020-09-03 at 15 36 56

**Comment by maxvisser** [comment]
The one above is the one implemented for 'normal vouchers'
image

**Comment by maxvisser** [comment]
on dev I found an issue when I am logged out. Maybe there is an action with no limit?
```
[2020-09-03 15:49:29] local.ERROR: Argument 1 passed to App\Models\FundProviderProduct::identityStockAvailable() must be of the type string, null given, called in /var/www/forus-backend/app/Http/Resources/ProductResource.php on line 86 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to App\\Models\\FundProviderProduct::identityStockAvailable() must be of the type string, null given, called in /var/www/forus-backend/app/Http/Resources/ProductResource.php on line 86 at /var/www/forus-backend/app/Models/FundProviderProduct.php:79)
```

**Comment by jamalv** [comment]
not sure if this is a known issue, but "bijdrage" is 1 by default, and I can not change it to 0 (it jumps back to 1);

- [ ] "bijdrage" should be 0 by default

Screenshot 2020-09-05 at 18 12 37

**Comment by jamalv** [comment]
@maxvisser @linda-90 @maartenfv 

Screenshot 2020-09-05 at 18 14 22

"Budget toevoegen" is a feels like a weird call to action here; should maybe just be bevestigen? Otherwise it should be "Actie toevoegen" I think.

**Comment by jamalv** [comment]
- [ ] Make gratis should **only** grey out the last field:

Screenshot 2020-09-05 at 18 17 25

**Review by maxvisser — APPROVED** [review]

**Review by maxvisser — APPROVED** [review]

**Pull request merged**
