### PR TITLE
Add docker

### PR DESCRIPTION
**Pull request by ateamcms**

### CODE REVIEW

**Comment by lexlog** [comment]
update - on the webshop last error is
```
Transition Rejection($id: 0 type: 6, message: The transition errored, detail: {"data":{"message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'products.id' in 'where clause' (SQL: select * from (select *, \n            CAST(IF(\n                ISNULL(`limit_total`),\n                GREATEST(`limit_per_identity` - `limit_per_identity_used`, 0),\n                GREATEST(`limit_total` - `limit_total_used`, 0)\n            ) AS SIGNED) as `limit_total_available`,\n            CAST(\n                GREATEST(`limit_per_identity` - `limit_per_identity_used`, 0) AS SIGNED\n            ) AS `limit_identity_available`,\n            CAST(GREATEST(\n                LEAST(\n                    IF(\n                        ISNULL(`limit_total`), \n                        GREATEST(`limit_per_identity` - `limit_per_identity_used`, 0), \n                        GREATEST(`limit_total` - `limit_total_used`, 0)\n                    ),\n                    GREATEST(`limit_per_identity` - `limit_per_identity_used`, 0)\n                ), 0\n            ) AS SIGNED) as `limit_available` from (select `products`.*, (select CAST(IFNULL(SUM(limit_multiplier), 1) as SIGNED) from `vouchers` where exists (select * from `funds` where `vouchers`.`fund_id` = `funds`.`id` and `funds`.`type` = subsidies and `funds`.`id` in (6)) and `product_id` is null and (`vouchers`.`expire_at` >= 2022-04-07 00:00:00 and exists (select * from `funds` where `vouchers`.`fund_id` = `funds`.`id` and date(`end_date`) >= 2022-04-07))) as `limit_multiplier`, (select cast(sum(`limit_total`) as signed) as `limit_total` from (select CAST(if(`limit_total_unlimited`, null, `limit_total`) as SIGNED) as `limit_total` from `fund_provider_products` where (exists (select * from `fund_providers` where `fund_provider_products`.`fund_provider_id` = `fund_providers`.`id` and exists (select * from `funds` where `fund_providers`.`fund_id` = `funds`.`id` and `funds`.`type` = subsidies and `funds`.`id` in (6)))) and `fund_provider_products`.`product_id` = `products`.`id` and `fund_provider_products`.`deleted_at` is null) as `reservations`) as `limit_total`, (select cast(sum(count_reservations) as signed) as count_reservations from (select (select CAST((`count_transactions` + `count_vouchers` + `count_reservations`) as SIGNED) as `used_total` from (select (select count(*) from `voucher_transactions` where `state` != canceled and `product_id` = `products`.`id` and (exists (select * from `vouchers` where `voucher_transactions`.`voucher_id` = `vouchers`.`id` and (`vouchers`.`expire_at` >= 2022-04-07 00:00:00 and exists (select * from `funds` where `vouchers`.`fund_id` = `funds`.`id` and date(`end_date`) >= 2022-04-07)) and (`fund_id` = 6) and exists (select * from `funds` where `vouchers`.`fund_id` = `funds`.`id` and `type` = subsidies)))) as `count_transactions`, (select count(*) from `vouchers` where not exists (select * from `product_reservations` where `vouchers`.`product_reservation_id` = `product_reservations`.`id` and `product_reservations`.`deleted_at` is null) and not exists (select * from `voucher_transactions` where `vouchers`.`id` = `voucher_transactions`.`voucher_id`) and `vouchers`.`product_id` = `products`.`id` and (`parent_id` is null and (`vouchers`.`expire_at` >= 2022-04-07 00:00:00 and exists (select * from `funds` where `vouchers`.`fund_id` = `funds`.`id` and date(`end_date`) >= 2022-04-07)) and (`fund_id` = 6) and exists (select * from `funds` where `vouchers`.`fund_id` = `funds`.`id` and `type` = subsidies))) as `count_vouchers`, (select count(*) from `product_reservations` where `state` not in (canceled, rejected) and not exists (select * from `voucher_transactions` where `product_reservations`.`voucher_transaction_id` = `voucher_transactions`.`id`) and `product_id` = `products`.`id` and (exists (select * from `vouchers` where `product_reservations`.`voucher_id` = `vouchers`.`id` and (`vouchers`.`expire_at` >= 2022-04-07 00:00:00 and exists (select * from `funds` where `vouchers`.`fund_id` = `funds`.`id` and date(`end_date`) >= 2022-04-07)) and (`fund_id` = 6) and exists (select * from `funds` where `vouchers`.`fund_id` = `funds`.`id` and `type` = subsidies))) and `product_reservations`.`deleted_at` is null) as `count_reservations`) as `reservations`) as `count_reservations` from (select * from `products` where `products`.`deleted_at` is null) as `product_tmp` where `product_tmp`.`id` = `products`.`id` and `products`.`deleted_at` is null) as `reservations`) as `limit_total_used`, (select cast(sum(`limit`) as signed) as `limit` from (select CAST(`limit_per_identity` * `limit_multiplier` AS SIGNED) as `limit` from `fund_provider_products` where (exists (select * from `fund_providers` where `fund_provider_products`.`fund_provider_id` = `fund_providers`.`id` and exists (select * from `funds` where `fund_providers`.`fund_id` = `funds`.`id` and `funds`.`type` = subsidies and `funds`.`id` in (6)))) and `fund_provider_products`.`product_id` = `products`.`id` and `fund_provider_products`.`deleted_at` is null) as `reservations`) as `limit_per_identity`, (select cast(sum(count_reservations) as signed) as count_reservations from (select (select CAST((`count_transactions` + `count_vouchers` + `count_reservations`) as SIGNED) as `used_total` from (select (select count(*) from `voucher_transactions` where `state` != canceled and `product_id` = `products`.`id` and (exists (select * from `vouchers` where `voucher_transactions`.`voucher_id` = `vouchers`.`id` and (`vouchers`.`expire_at` >= 2022-04-07 00:00:00 and exists (select * from `funds` where `vouchers`.`fund_id` = `funds`.`id` and date(`end_date`) >= 2022-04-07)) and (`fund_id` = 6) and exists (select * from `funds` where `vouchers`.`fund_id` = `funds`.`id` and `type` = subsidies)))) as `count_transactions`, (select count(*) from `vouchers` where not exists (select * from `product_reservations` where `vouchers`.`product_reservation_id` = `product_reservations`.`id` and `product_reservations`.`deleted_at` is null) and not exists (select * from `voucher_transactions` where `vouchers`.`id` = `voucher_transactions`.`voucher_id`) and `vouchers`.`product_id` = `products`.`id` and (`parent_id` is null and (`vouchers`.`expire_at` >= 2022-04-07 00:00:00 and exists (select * from `funds` where `vouchers`.`fund_id` = `funds`.`id` and date(`end_date`) >= 2022-04-07)) and (`fund_id` = 6) and exists (select * from `funds` where `vouchers`.`fund_id` = `funds`.`id` and `type` = subsidies))) as `count_vouchers`, (select count(*) from `product_reservations` where `state` not in (canceled, rejected) and not exists (select * from `voucher_transactions` where `product_reservations`.`voucher_transaction_id` = `voucher_transactions`.`id`) and `product_id` = `products`.`id` and (exists (select * from `vouchers` where `product_reservations`.`voucher_id` = `vouchers`.`id` and (`vouchers`.`expire_at` >= 2022-04-07 00:00:00 and exists (select * from `funds` where `vouchers`.`fund_id` = `funds`.`id` and date(`end_date`) >= 2022-04-07)) and (`fund_id` = 6) and exists (select * from `funds` where `vouchers`.`fund_id` = `funds`.`id` and `type` = subsidies))) and `product_reservations`.`deleted_at` is null) as `count_reservations`) as `reservations`) as `count_reservations` from (select * from `products` where `products`.`deleted_at` is null) as `product_tmp` where `product_tmp`.`id` = `products`.`id` and `products`.`deleted_at` is null) as `reservations`) as `limit_per_identity_used`, (select `reservations_subsidy_enabled` from `organizations` where `id` = `organization_id`) as `reservations_subsidy_enabled`, (select `reservations_budget_enabled` from `organizations` where `id` = `organization_id`) as `reservations_budget_enabled` from `products` where `id` = 68) as `products` where `products`.`deleted_at` is null) as `products` where `products`.`deleted_at` is null limit 1)","exception":"Illuminate\\Database\\QueryException","file":"/var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php","line":669,"trace":[{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php","line":629,"function":"runQueryCallback","class":"Illuminate\\Database\\Connection","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php","line":338,"function":"run","class":"Illuminate\\Database\\Connection","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php","line":2159,"function":"select","class":"Illuminate\\Database\\Connection","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php","line":2147,"function":"runSelect","class":"Illuminate\\Database\\Query\\Builder","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php","line":2619,"function":"Illuminate\\Database\\Query\\{closure}","class":"Illuminate\\Database\\Query\\Builder","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php","line":2148,"function":"onceWithColumns","class":"Illuminate\\Database\\Query\\Builder","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php","line":546,"function":"get","class":"Illuminate\\Database\\Query\\Builder","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php","line":530,"function":"getModels","class":"Illuminate\\Database\\Eloquent\\Builder","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php","line":143,"function":"get","class":"Illuminate\\Database\\Eloquent\\Builder","type":"->"},{"file":"/var/www/app/Http/Resources/ProductResource.php","line":121,"function":"first","class":"Illuminate\\Database\\Eloquent\\Builder","type":"->"},{"function":"App\\Http\\Resources\\{closure}","class":"App\\Http\\Resources\\ProductResource","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Support/Collection.php","line":638,"function":"array_map"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php","line":254,"function":"map","class":"Illuminate\\Support\\Collection","type":"->"},{"file":"/var/www/app/Http/Resources/ProductResource.php","line":130,"function":"map","class":"Illuminate\\Database\\Eloquent\\Collection","type":"->"},{"file":"/var/www/app/Http/Resources/ProductResource.php","line":76,"function":"getProductFunds","class":"App\\Http\\Resources\\ProductResource","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php","line":60,"function":"toArray","class":"App\\Http\\Resources\\ProductResource","type":"->"},{"function":"Illuminate\\Support\\{closure}","class":"Illuminate\\Support\\HigherOrderCollectionProxy","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Support/Collection.php","line":638,"function":"array_map"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php","line":61,"function":"map","class":"Illuminate\\Support\\Collection","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php","line":100,"function":"__call","class":"Illuminate\\Support\\HigherOrderCollectionProxy","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php","line":94,"function":"toArray","class":"Illuminate\\Http\\Resources\\Json\\ResourceCollection","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceResponse.php","line":39,"function":"resolve","class":"Illuminate\\Http\\Resources\\Json\\JsonResource","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php","line":201,"function":"toResponse","class":"Illuminate\\Http\\Resources\\Json\\ResourceResponse","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php","line":115,"function":"toResponse","class":"Illuminate\\Http\\Resources\\Json\\JsonResource","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":734,"function":"toResponse","class":"Illuminate\\Http\\Resources\\Json\\ResourceCollection","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":721,"function":"toResponse","class":"Illuminate\\Routing\\Router","type":"::"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":681,"function":"prepareResponse","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":130,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/var/www/app/Services/Forus/Session/Middleware/ForusSessionMiddleware.php","line":28,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":171,"function":"handle","class":"App\\Services\\Forus\\Session\\Middleware\\ForusSessionMiddleware","type":"->"},{"file":"/var/www/app/Http/Middleware/ClientTypeMiddleware.php","line":45,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":171,"function":"handle","class":"App\\Http\\Middleware\\ClientTypeMiddleware","type":"->"},{"file":"/var/www/app/Http/Middleware/ImplementationKeyMiddleware.php","line":37,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":171,"function":"handle","class":"App\\Http\\Middleware\\ImplementationKeyMiddleware","type":"->"},{"file":"/var/www/app/Http/Middleware/DomainMiddleware.php","line":45,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":171,"function":"handle","class":"App\\Http\\Middleware\\DomainMiddleware","type":"->"},{"file":"/var/www/app/Http/Middleware/LocaleMiddleware.php","line":25,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":171,"function":"handle","class":"App\\Http\\Middleware\\LocaleMiddleware","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php","line":41,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":171,"function":"handle","class":"Illuminate\\Routing\\Middleware\\SubstituteBindings","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":105,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":683,"function":"then","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":658,"function":"runRouteWithinStack","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":624,"function":"runRoute","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php","line":613,"function":"dispatchToRoute","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php","line":170,"function":"dispatch","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":130,"function":"Illuminate\\Foundation\\Http\\{closure}","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"},{"file":"/var/www/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php","line":60,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":171,"function":"handle","class":"Barryvdh\\Debugbar\\Middleware\\InjectDebugbar","type":"->"},{"file":"/var/www/vendor/fruitcake/laravel-cors/src/HandleCors.php","line":58,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":171,"function":"handle","class":"Fruitcake\\Cors\\HandleCors","type":"->"},{"file":"/var/www/vendor/fideloper/proxy/src/TrustProxies.php","line":57,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":171,"function":"handle","class":"Fideloper\\Proxy\\TrustProxies","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php","line":21,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":171,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php","line":21,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":171,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php","line":21,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":171,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php","line":27,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":171,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php","line":63,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":171,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php","line":105,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php","line":145,"function":"then","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php","line":110,"function":"sendRequestThroughRouter","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"},{"file":"/var/www/public/index.php","line":55,"function":"handle","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"}]},"status":500,"headers":"function(d){b||(b=zd(a));return d?(d=b[K(d)],void 0===d&&(d=null),d):b}","config":{"method":"GET","transformRequest":"function(a){return D(a)&&\n"[object File]"!==la.call(a)&&"[object Blob]"!==la.call(a)&&"[object FormData]"!==la.call(a)?eb(a):a}","transformResponse":"function wc(a,b){if(C(a)","paramSerializer":"function(a){if(!a)return"";var b=[];Qc(a,function(a,c){null===a||A(a)||B(a)||(H(a)?r(a,function(a){b.push(ba(c)+"="+ba(vc(a)))}):b.push(ba(c)+"="+ba(vc(a))))});return b.join("&")}","jsonpCallbackParam":"callback","params":{"fund_type":"subsidies","per_page":6},"headers":{"Accept":"application/json","Accept-Language":"nl","Authorization":"Bearer null","Client-Key":"general","Client-Type":"webshop"},"url":"http://localhost:8000/api/v1/platform/products/sample"},"statusText":"Internal Server Error","xhrStatus":"complete"})
```

Yaroslav in process of debugging

- [ ] fixed

**Comment by jamalv** [comment]
Backend didn't seemlessly work on M1 (apple silicon, ARM) - I had to make this change to get MySQL to run. Couldn't test if it works because I wasn't able to connect the frontends
image

**Comment by lexlog** [comment]
refinement - in review of @dev-rminds

**Comment by dev-rminds** [comment]
Tested on:
```
mac: intel/apple silicon
windows: x86
linux: x86
```

**Review by GerbenBosschieter — APPROVED** [review]

**Pull request merged**
