### PR TITLE
financial overview export add product vouchers data

### PR DESCRIPTION
**Pull request by aghimpu**

### CODE REVIEW

**Comment by dev-rminds** [comment]
Added a new functionality to make setting format of columns easier and updated the formats of some columns.
@lexlog @GerbenBosschieter could you please check if the new format is fine?


Example .csv/.xls files.
before: from dev
after: from this branch

[examples.zip](https://github.com/teamforus/forus-backend/files/10388803/examples.zip)

Top is old, bottom is new:
 
Screenshot 2023-01-11 at 06 03 05
Screenshot 2023-01-11 at 06 01 11

**Review by GerbenBosschieter — APPROVED** [review]

**Comment by GerbenBosschieter** [comment]
> Added a new functionality to make setting format of columns easier and updated the formats of some columns. @lexlog @GerbenBosschieter could you please check if the new format is fine?
> 
> Supported formats: https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Style/NumberFormat.php
> 
> Example .csv/.xls files. before: from dev after: from this branch
> 
> [examples.zip](https://github.com/teamforus/forus-backend/files/10388803/examples.zip)
> 
> Top is old, bottom is new:
> 
> Screenshot 2023-01-11 at 06 03 05
> 
> Screenshot 2023-01-11 at 06 01 11

Format is fine

**Comment by lexlog** [comment]
QA
- [ ] Tegoeden export - 500 error
Screenshot 2023-02-10 at 3 59 04 PM
```
{message: "Division by zero", exception: "DivisionByZeroError",…}
exception
: 
"DivisionByZeroError"
file
: 
"/var/www/forus-backend/app/Exports/FundsExport.php"
line
: 
153
message
: 
"Division by zero"
trace
: 
[,…]
0
: 
{file: "/var/www/forus-backend/app/Exports/FundsExport.php", line: 132, function: "getVoucherData",…}
1
: 
{function: "App\Exports\{closure}", class: "App\Exports\FundsExport", type: "->"}
2
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Collections/Collection.php",…}
3
: 
{,…}
4
: 
{file: "/var/www/forus-backend/app/Exports/FundsExport.php", line: 132, function: "map",…}
5
: 
{file: "/var/www/forus-backend/app/Exports/FundsExport.php", line: 73, function: "exportTransform",…}
6
: 
{file: "/var/www/forus-backend/app/Http/Controllers/Api/Platform/Organizations/FundsController.php",…}
7
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",…}
8
: 
{,…}
9
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Route.php", line: 261,…}
10
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Route.php", line: 204,…}
11
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 725,…}
12
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
13
: 
{file: "/var/www/forus-backend/app/Http/Middleware/ApiAuthMiddleware.php", line: 48,…}
14
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
15
: 
{file: "/var/www/forus-backend/app/Services/Forus/Session/Middleware/ForusSessionMiddleware.php",…}
16
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
17
: 
{file: "/var/www/forus-backend/app/Http/Middleware/ClientVersionMiddleware.php", line: 31,…}
18
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
19
: 
{file: "/var/www/forus-backend/app/Http/Middleware/ClientTypeMiddleware.php", line: 45,…}
20
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
21
: 
{file: "/var/www/forus-backend/app/Http/Middleware/ImplementationKeyMiddleware.php", line: 37,…}
22
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
23
: 
{file: "/var/www/forus-backend/app/Http/Middleware/DomainMiddleware.php", line: 45,…}
24
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
25
: 
{file: "/var/www/forus-backend/app/Http/Middleware/LocaleMiddleware.php", line: 27,…}
26
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
27
: 
{,…}
28
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
29
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
30
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 726,…}
31
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 703,…}
32
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 667,…}
33
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 656,…}
34
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",…}
35
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
36
: 
{file: "/var/www/forus-backend/vendor/fruitcake/laravel-cors/src/HandleCors.php", line: 52,…}
37
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
38
: 
{,…}
39
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
40
: 
{,…}
41
: 
{,…}
42
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
43
: 
{,…}
44
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
45
: 
{,…}
46
: 
{,…}
47
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
48
: 
{,…}
49
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
50
: 
{,…}
51
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
52
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",…}
53
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",…}
54
: 
{file: "/var/www/forus-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",…}
55
: 
{file: "/var/www/forus-backend/public/index.php", line: 63, function: "handle",…}
``` 
- [ ] Saldo - something with encoding 
Screenshot 2023-02-10 at 5 50 35 PM
Screenshot 2023-02-10 at 5 53 49 PM

@aghimpu could you take a look?

**Review by lexlog — CHANGES_REQUESTED** [review]
QA
- [x] Tegoeden export - 500 error on https://dev.forus.io/sponsor/#!/organizations/6/funds 
(dev+nijmegen@forus.io)
Screenshot 2023-02-10 at 3 59 04 PM

- [ ] Saldo - something with encoding 
Screenshot 2023-02-10 at 5 50 35 PM
Screenshot 2023-02-10 at 5 53 49 PM

- [x] need conflict resolve

@aghimpu could you take a look? ( and write ests if its > than 10mins)

**Comment by lexlog** [comment]
update QA:
tegoeden 500 issue fixed

left:
- [ ] encoding problem ( attaching two files )
[sponsor_Nijmegen_2023-02-22 13_35
[sponsor_Nijmegen_2023-02-22 13_36_33.csv](https://github.com/teamforus/forus-backend/files/10803239/sponsor_Nijmegen_2023-02-22.13_36_33.csv)
_55.csv](https://github.com/teamforus/forus-backend/files/10803238/sponsor_Nijmegen_2023-02-22.13_35_55.csv)

**Review by lexlog — APPROVED** [review]

**Pull request merged**
