### PR TITLE
Vouchers export, fix image export on other storage drivers than local

### PR DESCRIPTION
**Pull request by aghimpu**

### CODE REVIEW

**Comment by maxvisser** [comment]
Could you after export unlink the image as these instance don't have a large filesystem locally

**Comment by maxvisser** [comment]
@dev-rminds could you check this?

**Comment by dev-rminds** [comment]
@maxvisser 
This is related (show error message when export fails or there are no vouchers to be exported)
https://github.com/teamforus/forus-frontend/pull/839

**Comment by maxvisser** [comment]
This is a hotfix for master; the frontend part checked out from develop.

**Pull request merged**
