### PR TITLE
Epic.auth

### PR DESCRIPTION
**Pull request by dev-rminds**

### CODE REVIEW

**Comment by lexlog** [comment]
14300 lines changed :scream:

**Comment by GerbenBosschieter** [comment]
@dev-rminds from my perspective I set it up correctly. But still have to enter an e-mailadress. 

Screenshot 2022-07-21 at 09 45 55

Screenshot 2022-07-21 at 09 42 34

Screenshot 2022-07-21 at 09 48 30

**Comment by dev-rminds** [comment]
@GerbenBosschieter fixed on frontend

**Comment by GerbenBosschieter** [comment]
@dev-rminds found a bug when we enable **'hash_partner_deny'** to **fund_config**. Webshop will give empty page. If we would disable it does work.

Screenshot 2022-07-30 at 10 39 03
Screenshot 2022-07-30 at 10 35 31

**Review by GerbenBosschieter — APPROVED** [review]

**Pull request merged**
