### PR TITLE
Release/v0.32.0

### PR DESCRIPTION
**Pull request by GerbenBosschieter**
# Changelog:

- Feature: fund disregard
- Feature: sponsor now has the option to add more categories to the fund
- Improvement providers page (webshop): Filters are now dropdown search instead of dropdown
- Improvement subsidy budget voucher mail
- Bugfix: product voucher detail page
- Smaller frontend improvements

### CODE REVIEW

**Comment by GerbenBosschieter** [comment]
**Tested on: **
- Develop
- Staging

@dev-rminds We get a 500 error if we try to acces the webshop.  Presumably it has something to do with a check that the front end does **(wherePendingOrApprovedAndVoucherIsActive)**. We are not sure.

The problem only occurs if you visit the webshop while you are logged out. If you are logged in it's no problem. Console gives us the following feedback (funds?check_critera=1):

Screenshot 2022-01-26 at 16 06 42

**Comment by GerbenBosschieter** [comment]
@dev-rminds 

We get an 500 error when creating a fund (doesnt matter what fund type). The front end doesn;t give any feedback, console says 500 erro. But in reaility the fund is created and clicking confirm create new ones without anu visual feedback.

Also happends on dev.

image-error

**Comment by maxvisser** [comment]
```
[2022-01-27 14:37:14] dev.ERROR: Argument 1 passed to Illuminate\Database\Query\Builder::cleanBindings() must be of the type array, null given, called in /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 908 
{
    "userId": "0xa92eb3e163b15290d3b640ef88102807c26b2a82",
    "exception": "[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to Illuminate\\Database\\Query\\Builder::cleanBindings() must be of the type array, null given, called in /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 908 at /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2954)\n[stacktrace]\n#0 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(908): Illuminate\\Database\\Query\\Builder->cleanBindings(NULL)\n#1 /var/app/current/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Query\\Builder->whereIn('id', NULL)\n#2 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1388): Illuminate\\Database\\Eloquent\\Builder->forwardCallTo(Object(Illuminate\\Database\\Query\\Builder), 'whereIn', Array)\n#3 /var/app/current/app/Models/Fund.php(463): Illuminate\\Database\\Eloquent\\Builder->__call('whereIn', Array)\n#4 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(237): App\\Models\\Fund->App\\Models\\{closure}(Object(Illuminate\\Database\\Eloquent\\Builder))\n#5 /var/app/current/app/Models/Fund.php(465): Illuminate\\Database\\Eloquent\\Builder->where(Object(Closure))\n#6 /var/app/current/app/Http/Controllers/Api/Platform/Organizations/FundsController.php(96): App\\Models\\Fund->syncTags(NULL)\n#7 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Api\\Platform\\Organizations\\FundsController->store(Object(App\\Http\\Requests\\Api\\Platform\\Organizations\\Funds\\StoreFundRequest), Object(App\\Models\\Organization))\n#8 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Array)\n#9 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Api\\Platform\\Organizations\\FundsController), 'store')\n#10 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()\n#11 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()\n#12 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#13 /var/app/current/app/Http/Middleware/ApiAuthMiddleware.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#14 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\ApiAuthMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#15 /var/app/current/app/Services/Forus/Session/Middleware/ForusSessionMiddleware.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#16 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Services\\Forus\\Session\\Middleware\\ForusSessionMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#17 /var/app/current/app/Http/Middleware/ClientTypeMiddleware.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#18 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\ClientTypeMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#19 /var/app/current/app/Http/Middleware/ImplementationKeyMiddleware.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#20 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\ImplementationKeyMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#21 /var/app/current/app/Http/Middleware/DomainMiddleware.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#22 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\DomainMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#23 /var/app/current/app/Http/Middleware/LocaleMiddleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#24 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\LocaleMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#25 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#26 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#27 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#28 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#29 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#30 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))\n#31 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#32 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#33 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))\n#34 /var/app/current/vendor/fruitcake/laravel-cors/src/HandleCors.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#35 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#36 /var/app/current/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#37 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#38 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#39 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#40 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#41 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#42 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#43 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#44 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#45 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#46 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#47 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#48 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#49 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#50 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))\n#51 /var/app/current/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#52 {main}\n"
}```

**Review by RobinMeles — APPROVED** [review]

**Comment by GerbenBosschieter** [comment]
Can't approve my own PR. Did the acceptance testing. All good

**Pull request merged**
